In [2]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import numpy as np
bot_df = pd.read_csv("PLDeepLearnCTU13_10K - ClosenessCentrality.csv")
bot_df.head()
bot_feature = bot_df.copy()
bot_labels = bot_feature.pop('Lbls')
bot_feature = np.array(bot_feature)
bot_feature

array([[2.700e+01, 1.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [7.356e+03, 1.500e+01, 0.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [7.356e+03, 1.500e+01, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [2.700e+01, 1.380e+02, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.700e+01, 1.270e+02, 0.000e+00, ..., 2.000e+00, 0.000e+00,
        1.000e+00],
       [2.700e+01, 1.270e+02, 0.000e+00, ..., 1.000e+00, 0.000e+00,
        2.000e+00]])

In [3]:
bot_feature

array([[2.700e+01, 1.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [7.356e+03, 1.500e+01, 0.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [7.356e+03, 1.500e+01, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [2.700e+01, 1.380e+02, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.700e+01, 1.270e+02, 0.000e+00, ..., 2.000e+00, 0.000e+00,
        1.000e+00],
       [2.700e+01, 1.270e+02, 0.000e+00, ..., 1.000e+00, 0.000e+00,
        2.000e+00]])

In [4]:
a = bot_feature[0,0,0,0,0,0,0,0,0]

IndexError: too many indices for array: array is 2-dimensional, but 9 were indexed

In [5]:
a = bot_feature[0]

In [6]:
X = bot_feature[0,0]

In [7]:
a = bot_feature[0:,0:8]

In [8]:
bot_feature

array([[2.700e+01, 1.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [7.356e+03, 1.500e+01, 0.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [7.356e+03, 1.500e+01, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [2.700e+01, 1.380e+02, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.700e+01, 1.270e+02, 0.000e+00, ..., 2.000e+00, 0.000e+00,
        1.000e+00],
       [2.700e+01, 1.270e+02, 0.000e+00, ..., 1.000e+00, 0.000e+00,
        2.000e+00]])

In [9]:
bot_feature[0]

array([2.70e+01, 1.00e+00, 0.00e+00, 1.00e+00, 2.69e-06, 2.00e+00,
       0.00e+00, 0.00e+00, 0.00e+00])

In [10]:
a=bot_feature[0]

In [11]:
b=bot_feature[1]

In [12]:
d = distance.euclidean(a, b)

NameError: name 'distance' is not defined

In [13]:
from scipy.spatial import distance

In [14]:
d = distance.euclidean(a, b)

In [15]:
print("Euclidean distance: ",d)

Euclidean distance:  7329.013525027616
